openapi: 3.0.0
info:
  version: 1.0.0
  title: Nausf_UPUProtection Service
  description: AUSF UPU Protection Service
servers:
  - url: '{apiRoot}/nausf-upuprotection/v1'
    variables:
      apiRoot:
        default: 'https://example.com'
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
security:
  - {}
  - oAuth2ClientCredentials:
      - nausf-upuprotection
paths:
  '/{supi}/ue-upu':
    post:
      parameters:
        - name: supi
          in: path
          description: Identifier of the UE
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15}|nai-.+|.+)$'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                upuDataList:
                  type: array
                  items:
                    type: object
                    properties:
                      secPacket:
                        type: string
                        format: base64
                      defaultConfNssai:
                        type: array
                        items:
                          type: object
                          properties:
                            sst:
                              type: integer
                              minimum: 0
                              maximum: 255
                            sd:
                              type: string
                              pattern: '^[A-Fa-f0-9]{6}$'
                          required:
                            - sst
                        minItems: 1
                    oneOf:
                      - required:
                          - secPacket
                      - required:
                          - defaultConfNssai
                  minItems: 1
                upuAckInd:
                  type: boolean
              required:
                - upuDataList
                - upuAckInd
        required: true
      responses:
        '200':
          description: UpuSecurityInfo
          content:
            application/json:
              schema:
                type: object
                properties:
                  upuMacIausf:
                    type: string
                    pattern: '^[A-Fa-f0-9]{32}$'
                  counterUpu:
                    type: string
                    pattern: '^[A-Fa-f0-9]{4}$'
                  upuXmacIue:
                    type: string
                    pattern: '^[A-Fa-f0-9]{32}$'
                required:
                  - upuMacIausf
                  - counterUpu
        '503':
          description: Service Unavailable
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nausf-upuprotection: Access to the Nausf_UPUProtection API
  schemas:
    UpuInfo:
      type: object
      properties:
        upuDataList:
          type: array
          items:
            type: object
            properties:
              secPacket:
                type: string
                format: base64
              defaultConfNssai:
                type: array
                items:
                  type: object
                  properties:
                    sst:
                      type: integer
                      minimum: 0
                      maximum: 255
                    sd:
                      type: string
                      pattern: '^[A-Fa-f0-9]{6}$'
                  required:
                    - sst
                minItems: 1
            oneOf:
              - required:
                  - secPacket
              - required:
                  - defaultConfNssai
          minItems: 1
        upuAckInd:
          type: boolean
      required:
        - upuDataList
        - upuAckInd
    UpuSecurityInfo:
      type: object
      properties:
        upuMacIausf:
          type: string
          pattern: '^[A-Fa-f0-9]{32}$'
        counterUpu:
          type: string
          pattern: '^[A-Fa-f0-9]{4}$'
        upuXmacIue:
          type: string
          pattern: '^[A-Fa-f0-9]{32}$'
      required:
        - upuMacIausf
        - counterUpu
    UpuData:
      type: object
      properties:
        secPacket:
          type: string
          format: base64
        defaultConfNssai:
          type: array
          items:
            type: object
            properties:
              sst:
                type: integer
                minimum: 0
                maximum: 255
              sd:
                type: string
                pattern: '^[A-Fa-f0-9]{6}$'
            required:
              - sst
          minItems: 1
      oneOf:
        - required:
            - secPacket
        - required:
            - defaultConfNssai
    UpuMac:
      type: string
      pattern: '^[A-Fa-f0-9]{32}$'
    CounterUpu:
      type: string
      pattern: '^[A-Fa-f0-9]{4}$'
    UpuAckInd:
      type: boolean
externalDocs:
  description: 3GPP TS 29.509 V15.3.0; 5G System; Authentication Server Services
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.509'
