openapi: 3.0.0
info:
  version: 1.0.0
  title: JOSE Protected Message Forwarding API
  description: N32-f Message Forwarding
servers:
  - url: '{apiRoot}/n32f-forward/v1'
    variables:
      apiRoot:
        default: 'https://example.com'
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
externalDocs:
  description: >-
    3GPP TS 29.573 V15.1.0; 5G System; Public Land Mobile Network (PLMN)
    Interconnection; Stage 3
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/'
paths:
  /n32f-process:
    post:
      summary: N32-f Message Forwarding
      tags:
        - N32-f Forward
      operationId: PostN32fProcess
      requestBody:
        description: Custom operation N32-f Message Forwarding
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reformattedData
              properties:
                reformattedData:
                  type: object
                  required:
                    - ciphertext
                  properties:
                    protected:
                      type: string
                    unprotected:
                      type: object
                    header:
                      type: object
                    encrypted_key:
                      type: string
                    aad:
                      type: string
                    iv:
                      type: string
                    ciphertext:
                      type: string
                    tag:
                      type: string
                modificationsBlock:
                  type: array
                  items:
                    type: object
                    required:
                      - payload
                      - signature
                    properties:
                      payload:
                        type: string
                      protected:
                        type: string
                      header:
                        type: object
                      signature:
                        type: string
                  minItems: 1
      responses:
        '200':
          description: OK (Successful forwarding of reformatted message over N32-f)
          content:
            application/json:
              schema:
                type: object
                required:
                  - reformattedData
                properties:
                  reformattedData:
                    type: object
                    required:
                      - ciphertext
                    properties:
                      protected:
                        type: string
                      unprotected:
                        type: object
                      header:
                        type: object
                      encrypted_key:
                        type: string
                      aad:
                        type: string
                      iv:
                        type: string
                      ciphertext:
                        type: string
                      tag:
                        type: string
                  modificationsBlock:
                    type: array
                    items:
                      type: object
                      required:
                        - payload
                        - signature
                      properties:
                        payload:
                          type: string
                        protected:
                          type: string
                        header:
                          type: object
                        signature:
                          type: string
                    minItems: 1
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '411':
          description: Length Required
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '413':
          description: Payload Too Large
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '415':
          description: Unsupported Media Type
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '429':
          description: Too Many Requests
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '503':
          description: Service Unavailable
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        default:
          description: Unexpected error
components:
  schemas:
    FlatJweJson:
      type: object
      required:
        - ciphertext
      properties:
        protected:
          type: string
        unprotected:
          type: object
        header:
          type: object
        encrypted_key:
          type: string
        aad:
          type: string
        iv:
          type: string
        ciphertext:
          type: string
        tag:
          type: string
    FlatJwsJson:
      type: object
      required:
        - payload
        - signature
      properties:
        payload:
          type: string
        protected:
          type: string
        header:
          type: object
        signature:
          type: string
    N32fReformattedReqMsg:
      type: object
      required:
        - reformattedData
      properties:
        reformattedData:
          type: object
          required:
            - ciphertext
          properties:
            protected:
              type: string
            unprotected:
              type: object
            header:
              type: object
            encrypted_key:
              type: string
            aad:
              type: string
            iv:
              type: string
            ciphertext:
              type: string
            tag:
              type: string
        modificationsBlock:
          type: array
          items:
            type: object
            required:
              - payload
              - signature
            properties:
              payload:
                type: string
              protected:
                type: string
              header:
                type: object
              signature:
                type: string
          minItems: 1
    N32fReformattedRspMsg:
      type: object
      required:
        - reformattedData
      properties:
        reformattedData:
          type: object
          required:
            - ciphertext
          properties:
            protected:
              type: string
            unprotected:
              type: object
            header:
              type: object
            encrypted_key:
              type: string
            aad:
              type: string
            iv:
              type: string
            ciphertext:
              type: string
            tag:
              type: string
        modificationsBlock:
          type: array
          items:
            type: object
            required:
              - payload
              - signature
            properties:
              payload:
                type: string
              protected:
                type: string
              header:
                type: object
              signature:
                type: string
          minItems: 1
    DataToIntegrityProtectAndCipherBlock:
      type: object
      required:
        - dataToEncrypt
      properties:
        dataToEncrypt:
          type: array
          items:
            type: object
          minItems: 1
    DataToIntegrityProtectBlock:
      type: object
      properties:
        metaData:
          type: object
          required:
            - n32fContextId
            - messageId
            - authorizedIpxId
          properties:
            n32fContextId:
              type: string
            messageId:
              type: string
            authorizedIpxId:
              type: string
        requestLine:
          type: object
          required:
            - method
            - scheme
            - authority
            - path
            - protocolVersion
          properties:
            method:
              anyOf:
                - type: string
                  enum:
                    - GET
                    - PUT
                    - POST
                    - DELETE
                    - PATCH
                    - HEAD
                    - OPTIONS
                    - CONNECT
                    - TRACE
                - type: string
            scheme:
              anyOf:
                - type: string
                  enum:
                    - http
                    - https
                - type: string
            authority:
              type: string
            path:
              type: string
            protocolVersion:
              type: string
            queryFragment:
              type: string
        statusLine:
          type: string
        headers:
          type: array
          items:
            type: object
            required:
              - header
              - value
            properties:
              header:
                type: string
              value:
                oneOf:
                  - type: string
                  - type: object
                    required:
                      - encBlockIndex
                    properties:
                      encBlockIndex:
                        type: integer
                        minimum: 0
          minItems: 1
        payload:
          type: array
          items:
            type: object
            required:
              - iePath
              - ieValueLocation
              - value
            properties:
              iePath:
                type: string
              ieValueLocation:
                anyOf:
                  - type: string
                    enum:
                      - URI_PARAM
                      - HEADER
                      - BODY
                      - MULTIPART_BINARY
                  - type: string
              value:
                type: object
          minItems: 1
    RequestLine:
      type: object
      required:
        - method
        - scheme
        - authority
        - path
        - protocolVersion
      properties:
        method:
          anyOf:
            - type: string
              enum:
                - GET
                - PUT
                - POST
                - DELETE
                - PATCH
                - HEAD
                - OPTIONS
                - CONNECT
                - TRACE
            - type: string
        scheme:
          anyOf:
            - type: string
              enum:
                - http
                - https
            - type: string
        authority:
          type: string
        path:
          type: string
        protocolVersion:
          type: string
        queryFragment:
          type: string
    HttpHeader:
      type: object
      required:
        - header
        - value
      properties:
        header:
          type: string
        value:
          oneOf:
            - type: string
            - type: object
              required:
                - encBlockIndex
              properties:
                encBlockIndex:
                  type: integer
                  minimum: 0
    HttpPayload:
      type: object
      required:
        - iePath
        - ieValueLocation
        - value
      properties:
        iePath:
          type: string
        ieValueLocation:
          anyOf:
            - type: string
              enum:
                - URI_PARAM
                - HEADER
                - BODY
                - MULTIPART_BINARY
            - type: string
        value:
          type: object
    MetaData:
      type: object
      required:
        - n32fContextId
        - messageId
        - authorizedIpxId
      properties:
        n32fContextId:
          type: string
        messageId:
          type: string
        authorizedIpxId:
          type: string
    Modifications:
      type: object
      required:
        - identity
      properties:
        identity:
          type: string
        operations:
          type: array
          items:
            type: object
            properties:
              op:
                anyOf:
                  - type: string
                    enum:
                      - add
                      - copy
                      - move
                      - remove
                      - replace
                      - test
                  - type: string
              path:
                type: string
              from:
                type: string
              value:
                nullable: true
            required:
              - op
              - path
          minItems: 1
    IndexToEncryptedValue:
      type: object
      required:
        - encBlockIndex
      properties:
        encBlockIndex:
          type: integer
          minimum: 0
    EncodedHttpHeaderValue:
      oneOf:
        - type: string
        - type: object
          required:
            - encBlockIndex
          properties:
            encBlockIndex:
              type: integer
              minimum: 0
