openapi: 3.0.0
info:
  description: Nnwdaf_AnalyticsInfo Service API
  version: 1.0.1
  title: Nnwdaf_AnalyticsInfo
externalDocs:
  description: 3GPP TS 29.520 V15.3.0; 5G System; Network Data Analytics Services.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.520/'
security:
  - {}
  - oAuth2ClientCredentials:
      - nnwdaf-analyticsinfo
servers:
  - url: '{apiRoot}/nnwdaf-analyticsinfo/v1'
    variables:
      apiRoot:
        default: 'https://example.com'
        description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
paths:
  /analytics:
    get:
      parameters:
        - name: event-id
          in: query
          description: Identify the analytics.
          required: true
          schema:
            anyOf:
              - type: string
                enum:
                  - LOAD_LEVEL_INFORMATION
              - type: string
                description: >
                  This string provides forward-compatibility with future
                  extensions to the enumeration but is not used to encode
                  content defined in the present version of this API.
            description: >
              Possible values are - LOAD_LEVEL_INFORMATION: Represent the
              analytics of load level information of corresponding network slice
              instance.
        - name: event-filter
          in: query
          description: Identify the analytics when the eventId is "Load_Level_Information".
          required: false
          content:
            application/json:
              schema:
                type: object
                properties:
                  anySlice:
                    type: boolean
                    description: >-
                      FALSE represents not applicable for all slices. TRUE
                      represents applicable for all slices.
                  snssais:
                    type: array
                    items:
                      type: object
                      properties:
                        sst:
                          type: integer
                          minimum: 0
                          maximum: 255
                        sd:
                          type: string
                          pattern: '^[A-Fa-f0-9]{6}$'
                      required:
                        - sst
                    minItems: 1
                    description: >-
                      Identification(s) of network slice to which the
                      subscription belongs. When eventId is
                      "Load_level_Information", either information about
                      slice(s) identified by snssai, or anySlice set to "TRUE"
                      shall be included.
                  not:
                    required:
                      - anySlice
                      - snssais
        - name: supported-features
          in: query
          description: To filter irrelevant responses related to unsupported features
          schema:
            type: string
            pattern: '^[A-Fa-f0-9]*$'
      responses:
        '200':
          description: >-
            The individual PCF session biding session binding information
            resource matching the query parameter(s) is returned.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sliceLoadLevelInfos:
                    type: array
                    items:
                      type: object
                      properties:
                        loadLevelInformation:
                          type: integer
                          description: >-
                            Load level information of the network slice
                            instance.
                        snssais:
                          type: array
                          items:
                            type: object
                            properties:
                              sst:
                                type: integer
                                minimum: 0
                                maximum: 255
                              sd:
                                type: string
                                pattern: '^[A-Fa-f0-9]{6}$'
                            required:
                              - sst
                          minItems: 1
                          description: >-
                            Identification(s) of network slice to which the
                            subscription.
                      required:
                        - loadLevelInformation
                        - snssais
                    minItems: 1
                    description: The slices and their load level information.
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '403':
          description: Forbidden
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '404':
          description: Indicates that the NWDAF Analytics resource does not exist.
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '406':
          description: 406 Not Acceptable
        '414':
          description: URI Too Long
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '429':
          description: Too Many Requests
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        '503':
          description: Service Unavailable
          content:
            application/problem+json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                  title:
                    type: string
                  status:
                    type: integer
                  detail:
                    type: string
                  instance:
                    type: string
                  cause:
                    type: string
                  invalidParams:
                    type: array
                    items:
                      type: object
                      properties:
                        param:
                          type: string
                        reason:
                          type: string
                      required:
                        - param
                    minItems: 1
        default:
          description: Generic Error
components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nnwdaf-analyticsinfo: Access to the Nnwdaf_AnalyticsInfo API
  schemas:
    AnalyticsData:
      type: object
      properties:
        sliceLoadLevelInfos:
          type: array
          items:
            type: object
            properties:
              loadLevelInformation:
                type: integer
                description: Load level information of the network slice instance.
              snssais:
                type: array
                items:
                  type: object
                  properties:
                    sst:
                      type: integer
                      minimum: 0
                      maximum: 255
                    sd:
                      type: string
                      pattern: '^[A-Fa-f0-9]{6}$'
                  required:
                    - sst
                minItems: 1
                description: Identification(s) of network slice to which the subscription.
            required:
              - loadLevelInformation
              - snssais
          minItems: 1
          description: The slices and their load level information.
    EventFilter:
      type: object
      properties:
        anySlice:
          type: boolean
          description: >-
            FALSE represents not applicable for all slices. TRUE represents
            applicable for all slices.
        snssais:
          type: array
          items:
            type: object
            properties:
              sst:
                type: integer
                minimum: 0
                maximum: 255
              sd:
                type: string
                pattern: '^[A-Fa-f0-9]{6}$'
            required:
              - sst
          minItems: 1
          description: >-
            Identification(s) of network slice to which the subscription
            belongs. When eventId is "Load_level_Information", either
            information about slice(s) identified by snssai, or anySlice set to
            "TRUE" shall be included.
        not:
          required:
            - anySlice
            - snssais
    EventId:
      anyOf:
        - type: string
          enum:
            - LOAD_LEVEL_INFORMATION
        - type: string
          description: >
            This string provides forward-compatibility with future extensions to
            the enumeration but is not used to encode content defined in the
            present version of this API.
      description: >
        Possible values are - LOAD_LEVEL_INFORMATION: Represent the analytics of
        load level information of corresponding network slice instance.
